"""Actions are a series of keys that determine how data flows."""
"""for viewer"""
UPDATE_CAMERA_TRANSLATION = 'UPDATE_CAMERA_TRANSLATION'
UPDATE_CAMERA_ROTATION = 'UPDATE_CAMERA_ROTATION'
UPDATE_CAMERA_FOV = 'UPDATE_CAMERA_FOV'
UPDATE_RESOLUTION = 'UPDATE_RESOLUTION'
UPDATE_RENDER_TYPE = 'UPDATE_RENDER_TYPE'
"""for nerf backend"""
# update the scene state
UPDATE_STATE = 'UPDATE_STATE'
UPDATE_RENDER_RESULT = 'UPDATE_RENDER_RESULT'
